// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgrfhsfpbofdrfhqkwsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtncmZoc2ZwYm9mZHJmaHFrd3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1MTY2OTksImV4cCI6MjA1MDA5MjY5OX0.gtcD31Dz_WFlxVCxUYZPYGFawgkFjfsEFxsBysgps-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);